name: php
type: "php:5.6"
build:
    flavor: drupal
access:
    ssh: contributor
relationships:
    database: "mysql:mysql"
web:
    locations:
        '/':
            root: 'docroot'
            passthru: '/index.php'
disk: 2048
mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public/docroot ; drush core-cron"
